### ISSUE TITLE
test failure with python 3.12b4

### ISSUE THREAD

**Issue by keszybz** [Quansight-Labs/ndindex#158]
Hi!

I'm building a package for Fedora 39, which will use python3.12, and I'm getting the following failure:
```
=================================== FAILURES ===================================
___________________________________ test_eq ____________________________________

    @example([1, 2])
>   @given(ndindices)

ndindex/tests/test_ndindex.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

idx = slice(None, None, None)

    @example([1, 2])
    @given(ndindices)
    def test_eq(idx):
        index = ndindex(idx)
        new = type(index)(*index.args)
    
        if isinstance(new.raw, np.ndarray):
            # trying to get a single value out of comparing two arrays requires all sorts of special handling, just let numpy do it
            assert np.array_equal(new.raw, index.raw)
        else:
            assert new.raw == index.raw
    
        assert (new == index)
        assert (new.raw == index)
        assert (new == index.raw)
        assert (index == new)
        assert (index.raw == new)
        assert (index == new.raw)
    
        assert (index.raw == index)
        assert hash(new) == hash(index)
        assert (index == index.raw)
        assert not (index == 'a')
        assert not ('a' == index)
        assert (index != 'a')
        assert ('a' != index)
    
        try:
            h = hash(idx)
        except TypeError:
            pass
        else:
>           assert hash(index) == h
E           assert 6902795556364740818 == 4032618106351268893
E            +  where 6902795556364740818 = hash(Slice(None, None, None))
E           Falsifying example: test_eq(
E               idx=slice(None, None, None),
E           )

ndindex/tests/test_ndindex.py:50: AssertionError
```

python3-3.12.0~b4-1.fc39.x86_64
(With python3-3.11.4-1.fc38.x86_64 the tests pass fine.)

**Comment by asmeurer** [comment]
Apparently Python 3.12 makes slices hashable. Interesting.

**Comment by asmeurer** [comment]
I'm curious how you actually did this seeing as NumPy itself doesn't support building in Python 3.12 yet.

**Comment by asmeurer** [comment]
Got it working with numpy nightly wheels https://scientific-python.org/specs/spec-0004/

**Comment by keszybz** [comment]
Thanks!

> I'm curious how you actually did this seeing as NumPy itself doesn't support building in Python 3.12 yet.

Somebody has to take the first step ;)   Fedora 39 has a mostly-complete python stack recompiled for python 3.12.

**Comment by asmeurer** [comment]
Sure, but I take it you're using the numpy development branch? Work in NumPy to get it to even compile in 3.12 is ongoing, due to the removal of distutils from the standard library which completely changes the NumPy build process.

**Comment by keszybz** [comment]
I'm not involved in the work on numpy directly, so I don't know the details. FWIW, the numpy package is built using this spec file: https://src.fedoraproject.org/rpms/numpy/blob/rawhide/f/numpy.spec. The last few commits are about compat with python 3.12, but it seems that only minor changes were required.
