### ISSUE TITLE
install requirements does not add Cython

### ISSUE THREAD

**Issue by Ragnar-the-mighty** [Quansight-Labs/ndindex#190]
The 1.9 release added Cython requirements but the install requirements does not list Cython so I get

9.684   File "/tmp/easy_install-m17cnkk1/ndindex-1.9/setup.py", line 10, in <module>
9.684     .txt files include the exact pins, and are useful for deployments with
9.684 ModuleNotFoundError: No module named 'Cython'

**Comment by asmeurer** [comment]
Yeah, sorry about this. I messed up the release process and it didn't actually upload wheels. I am fixing it at #189 (should be done within the hour assuming nothing else goes wrong).

**Comment by asmeurer** [comment]
This should be fixed now. 1.9.1 has wheels for all platforms uploaded. Let me know if you encounter any further problems. 

(and yes, I do need to update the docs, but that should only be necessary for development)
