### ISSUE TITLE
ndarray(x) == NDIndex(x) and NDIndex(x) == ndarray(x) should return a consistent result

### ISSUE THREAD

**Issue by telamonian** [Quansight-Labs/ndindex#95]
Currently, testing the equality of `NDIndex` vs `ndarray` objects changes depending on the order of the objects:

```python
>>> ndindex([0, 1]) == np.array([0, 1])
True
>>> np.array([0, 1]) == ndindex([0, 1])
array([False, False])
```

Ideally, the result should not change in this case, ie

```python
a = (ndindex([0, 1]) == np.array([0, 1]))
b = (np.array([0, 1]) == ndindex([0, 1]))
np.all(a == b) == True
```

**Comment by telamonian** [comment]
> Not to mention this behavior
> 
> ```python
> >>> ndindex([0, 1]) == np.array([0, 1])
> True
> >>> np.array([0, 1]) == ndindex([0, 1])
> array([False, False])
> ```

@asmeurer In your ideal world, which of the following would be the behavior for `ndarray` vs `NDIndex` equality?

A)

```
ndindex([0, 1]) == np.array([0, 1])
> array([True, True])
np.array([0, 1]) == ndindex([0, 1])
> array([True, True])
```

or B)

```
ndindex([0, 1]) == np.array([0, 1])
> True
np.array([0, 1]) == ndindex([0, 1])
> True
```

Both can be done. I'd argue for A), since that's now the expected behavior for "array-like" objects (as defined by numpy as of 1.17, I think?). B) is also doable, but it will have to have the side-effect that `isinstance(ndindex([0, 1]), np.ndarray)` is `True`

_Originally posted by @telamonian in https://github.com/Quansight/ndindex/issues/88#issuecomment-715651629_

**Comment by telamonian** [comment]
I would prefer it if I could make them both give True. == giving an array makes very basic things like checking if an index is in a list or dictionary difficult, because bool() fails on arrays. And anyway, an ndindex array index object is *not* an array-like. See https://quansight.github.io/ndindex/type-confusion.html#integerarray-and-booleanarray

_Originally posted by @asmeurer in https://github.com/Quansight/ndindex/issues/88#issuecomment-715651906_

**Comment by telamonian** [comment]
I'll look into this. I already got a prototype PR working, but my current approach makes `ArrayIndex` into a subclass of `np.ndarray`, which may have some undesired side-effects

**Comment by asmeurer** [comment]
Yeah, I'll have to see what the consequences of that are, but it may be not worth it. I didn't realize there was any way to bypass `ndarray.__eq__` but I guess it makes sense that it might be possible if you also subclass from ndarray.

**Comment by telamonian** [comment]
Okay, so let's say we have a bin op `⊗` like:

```
a ⊗ b
```

where `a` is an `ndarray` and `b` is an instance of some user-defined class `B`. Looking through docs, NEPs, and the source code, it looks like there's actually at least 4 different ways to override dispatch so that `b.__op__(a)` gets called, instead of `a.__op__(b)`:

1) Make `B` an `ndarray` subclass:

```python
class B(ndarray):
....
```

2) Add an `__array__` method to `B`

```python
class B:
    # should return an "array-like", which is what will actually participate in the bin op
    __array__(self, dtype=None):
        # for example
        if dtype is not None:
            return self.raw.asdtype(dtype)
        else:
            return self.raw
```

3) Add an `__array_priority__` class parameter to `B`:

```python
class B:
    # if defined, numpy will compare __array_priority__ of `a ⊗ b` and then dispatch to the "winner"
    __array_priority__ = 1
```

4) Add a `__array_ufunc__` method to `B` (and optionally also a `__array_func__` method):

```python
```

**Comment by telamonian** [comment]
@asmeurer So my proposal would be to to implement either 3) or 4) from the above for `ArrayIndex`. Here's a short list of pros and cons for each

3) Add `__array_priority__`:
    - pro:
        - simplest of the possibilities, literally a one-liner
    - cons:
        - `np.equal(a, b)` and `np.array_equal` give nonsense results (same as current behavior)
        - (probably a non-issue) if a is a proper `ndarray` subclass AND defines `a.__array_priority__ > b.__array_priority__`, there could be some unexpected behavior

4) Add `__array_ufunc__`:
    - pro:
        - strongly enforces the notion that [`ArrayIndex`s are not arrays](https://quansight.github.io/ndindex/type-confusion.html#integerarray-and-booleanarray), as calls like `np.equal(a, b)` and `np.array_equal(a, b)` will raise `TypeError`
    - con:
        - the extra `TypeError`s may be surprising behavior to certain users, since they don't occur for generic user classes

I'm leaning towards 4). It seems like the most robust option, and I think it meshes well with (what I've gleaned from the ndindex docs and your comments on) your design intentions for ndindex.

We can also try pinging @rgommers here to see what he/the numpy team would consider to be the best practice here

**Comment by telamonian** [comment]
There's now a PR for 4) over at #96
